name: build-docs

on:
  pull_request:
    types: [labeled, synchronize, closed]

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    if: >-
      github.event.action != 'closed' &&
      contains(github.event.pull_request.labels.*.name, 'check-page')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate API Reference
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: ./generate_api.sh "$BASE_REF"

      - name: Build docs
        run: mkdocs build -f mkdocs.yaml --strict

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site/
          action: deploy

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: rossjrw/pr-preview-action@v1
        with:
          action: remove
